"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().resolve().parent.parent


def _env_bool(nome: str, padrao: str) -> bool:
    return os.getenv(nome, padrao).strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", "true")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = (
            "django-insecure--p5o)0ce@c7z8m^&@c2g00arr!rpdwhg5&l1umuh@)k920-86*"
        )
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY é obrigatório quando DJANGO_DEBUG=False."
        )

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
    if h.strip()
]

DJANGO_ADMIN_URL = os.getenv("DJANGO_ADMIN_URL", "admin/").strip("/")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "corsheaders",
    "rest_framework",
    "artigos",
    "chat",
    "autenticacao",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "smartpapers"),
        "USER": os.getenv("POSTGRES_USER", "smartpapers_user"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "smartpapers_pass"),
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

# Cache compartilhado (cancelamento de requisições entre workers).
# Sem REDIS_URL, usa LocMemCache — que só enxerga o próprio processo, portanto
# o cancelamento funciona apenas com um único worker do gunicorn.
REDIS_URL = os.getenv("REDIS_URL", "").strip()
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 10},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
EMBEDDING_DIM = 768
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Provedores de IA ---
# "1"/"true" habilita o Ollama (modelo local). Em servidores sem recursos,
# deixe em "0" e use apenas o Gemini: o frontend esconde a opção Ollama e o
# backend recusa solicitações com provider "ollama".
OLLAMA_ENABLED = (
    os.getenv("OLLAMA_ENABLED", "1").strip().lower()
    in ("1", "true", "yes", "on")
)


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "agente": "20/min",
        "modelos": "10/min",
        "pesquisa": "60/min",
        "login": "20/min",
        "registro": "10/min",
    },
    # Quantos proxies ficam entre o cliente e o gunicorn. Com nginx na frente
    # (produção), defina DJANGO_NUM_PROXIES=1 para os rate limits e o bloqueio
    # por IP usarem o IP real do cliente (via X-Forwarded-For).
    "NUM_PROXIES": int(os.getenv("DJANGO_NUM_PROXIES", "0")),
}


# CORS e cookies de sessão para o frontend (origem separada em dev;
# em produção defina DJANGO_CORS_ALLOWED_ORIGINS / DJANGO_CSRF_TRUSTED_ORIGINS).
_DJANGO_ORIGENS_PADRAO = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",")
    if o.strip()
] or _DJANGO_ORIGENS_PADRAO

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
] or _DJANGO_ORIGENS_PADRAO


# --- HTTPS/produção ---
# O Django fica atrás do nginx (ou load balancer) que termina o TLS; o header
# abaixo + X-Forwarded-Proto fazem request.is_secure() funcionar.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Padrão seguro: quando DEBUG=False, cookies de sessão/CSRF só via HTTPS e
# redirecionamento para HTTPS. Pode ser desligado com env em infraestrutura
# que termina TLS externamente.
SESSION_COOKIE_SECURE = _env_bool(
    "DJANGO_SECURE_COOKIES", "false" if DEBUG else "true"
)
CSRF_COOKIE_SECURE = _env_bool(
    "DJANGO_SECURE_COOKIES", "false" if DEBUG else "true"
)
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SSL_REDIRECT", "false" if DEBUG else "true")
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_HSTS_SECONDS", "31536000" if not DEBUG else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "padrao": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "padrao",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "artigos": {"level": "INFO", "propagate": True},
        "chat": {"level": "INFO", "propagate": True},
        "django.request": {"level": "WARNING", "propagate": True},
    },
}
